export const NEW_REMINDER_REQUEST="NEW_REMINDER_REQUEST";
export const NEW_REMINDER_SUCCESS="NEW_REMINDER_SUCCESS";
export const NEW_REMINDER_FAIL="NEW_REMINDER_FAIL";

export const GET_REMINDER_REQUEST="GET_REMINDER_REQUEST";
export const GET_REMINDER_SUCCESS="GET_REMINDER_SUCCESS";
export const GET_REMINDER_FAIL="GET_REMINDER_FAIL";